<a href="https://colab.research.google.com/github/Mohitsaini2028/Machine-Learning/blob/main/basic_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [4]:
# Creating a rank 2 Array
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr2.dtype

dtype('int64')

In [6]:
# Forced Datatype
x = np.array([1, 2], dtype = np.int64) 

Math Operations on DataType array

In [7]:
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)

In [8]:
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)

In [11]:
np.any([[True,False],[True,True]])

True

In [12]:
np.zeros([4, 3],
         dtype = np.int32,
         order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [13]:
np.ones([4, 3],
        dtype = np.int32,
        order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [14]:
np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[48218032,        0,        0],
       [       0,        0,        0],
       [       0,        0,        0],
       [       0,        0,        0]], dtype=int32)

In [15]:
var = "AmazingWorld"
 
arr = np.fromiter(var, dtype = 'U2')
arr
 

array(['A', 'm', 'a', 'z', 'i', 'n', 'g', 'W', 'o', 'r', 'l', 'd'],
      dtype='<U2')